google_customer_reviews.settings:
  type: config_object
  label: 'Google Customer Reviews settings'
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID'
    optin_style:
      type: string
      label: 'Checkout opt-in style'
    estimated_delivery_days:
      type: integer
      label: 'Estimated days to delivery'